files:
  - source: /config/locales/zealot/zh-CN.yml
    translation: /config/locales/zealot/%two_letters_code%.yml
    escape_quotes: 1
    translate_content: 0
    escape_special_characters: 0
  - source: /config/locales/simple_form/simple_form.zh-CN.yml
    translation: /config/locales/simple_form/simple_form.%two_letters_code%.yml
    escape_quotes: 1
    translate_content: 0
    escape_special_characters: 0
