default: &base
  version: <%= ENV['ZEALOT_VERSION'] || 'development' %>
  vcs_ref: <%= ENV['ZEALOT_VCS_REF'] %>
  register_enabled: <%= ENV['ZEALOT_REGISTER_ENABLED'] || 'true' %>
  cron_jobs:
    clean_old_releases:
      cron: '0 6 * * *'
      class: 'CleanOldReleasesJob'
      queue: schedule
    reset_for_demo_mode:
      cron: '0 0 * * *'
      class: 'ResetForDemoModeJob'
      queue: schedule

development:
  <<: *base

test:
  <<: *base

production:
  <<: *base