default: &base
  version: 4.0.0
  cron_jobs:
    clean_old_releases:
      cron: '0 6 * * *'
      class: 'CleanOldReleasesJob'
      queue: schedule

development:
  <<: *base

test:
  <<: *base

production:
  <<: *base