name: Publish Release Docker Image
on:
  push:
    tags:
      - "*"

jobs:
  push_to_registry:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Get build date
      id: build_date
      run: echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S %z')" >> $GITHUB_OUTPUT

    - name: Get the version
      id: version
      run: echo "GIT_TAG=$(echo ${GITHUB_REF:10})" >> $GITHUB_OUTPUT

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker metadata
      id: metadata
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Build and Push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        labels: ${{ steps.metadata.outputs.labels }}
        tags: |
          ${{ steps.metadata.outputs.tags }}
          ${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:latest
        platforms: linux/amd64,linux/arm64,linux/arm/v7
        build-args: |
          REPLACE_CHINA_MIRROR=false
          VCS_REF=${{ github.sha }}
          BUILD_DATE=${{ steps.build_date.outputs.BUILD_DATE }}
          TAG=${{ steps.version.outputs.GIT_TAG }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.CR_PAT }}
